### ISSUE TITLE
This project is NOT dead. Read for details!

### ISSUE THREAD

**Issue by SKCro** [SKCro/WebTV-HD#14]
Due to the relative inactivity of this repo, you might think that this project is dead or abandoned. However, that couldn't be further from the truth - I'm working on the **massive** 200th update, which will come with loads of improvements (mainly a directory restructure, scripting overhaul, new home pages, and more!)

<sub>Oh, and here's a small sneak peek ;)</sub>

![image](https://github.com/SKCro/WebTV-HD/assets/55817746/a9005697-9b54-44c0-8980-6c063314b675)

Thank you all for your interest in this project! Feel free to ask questions in the comments below.

**Comment by Eduardo7881** [comment]
hey yo. wtf is this code 💀

window.doAlert = function(text){
    var taunt = ['nice try lmfao', 'inspect element ain\'t gonna work here kid', 'you are a big mac from McDonald\'s kid'];
    dialogMessage.textContent = text;
    openDialog();
    function checkDialogState(){
      if (dialogMessage.textContent !== text && !taunt.includes(dialogMessage.textContent) && dialogMessage.textContent !== '') {
        dialogMessage.textContent = taunt[Math.floor(Math.random() * taunt.length)];
        console.error('nice try fucker');
        setTimeout(function(){dialogMessage.textContent = text;},190);
      }
    }
    intervalId = setInterval(checkDialogState,10);
    window.resetDialogChecker = function(){
      clearInterval(intervalId);
      dialogMessage.textContent = text;
    };
  };

**Comment by SKCro** [comment]
@Eduardo7881 that was removed long ago lmfao

**Comment by home-gihub** [comment]
any updates?
🤔

**Comment by SKCro** [comment]
@home-gihub to be honest, not really. The update probably isn't going to release with all the features I had anticipated, but I'll try to finish as much as I can within a reasonable amount of time.
I've been distracted with other life stuff too, so that definitely doesn't help either :P

**Comment by home-gihub** [comment]
> @home-gihub to be honest, not really. The update probably isn't going to release with all the features I had anticipated, but I'll try to finish as much as I can within a reasonable amount of time. I've been distracted with other life stuff too, so that definitely doesn't help either :P

okay 😜

**Comment by SKCro** [comment]
Gonna close this since I've updated the repo recently. Merry Christmas!
