### ISSUE TITLE
Music does not work on portait on phone

### ISSUE THREAD

**Issue by Flamelord626** [SKCro/WebTV-HD#15]
Hi so I can't click on the play button for the music 
On my phone in portrait landscape works though the res of my Samsung galaxy a13 is 720x1600  here is the link for the image https://files.catbox.moe/yrcl8e.jpg
I think the issue is that the horizontal resolution is so small that the ui your using just does not work
It should be pretty easy to reproduce this issue 
Thanks and have a good day? Well right now for me it's 1:53 anyways
And I was using chrome

**Comment by SKCro** [comment]
Unfortunately, this probably can't be fixed because the UI for audios is handled by the browser itself and not by WebTV HD. I could try adding a `min-height` attribute to the audio, but it might not solve the problem
