### ISSUE TITLE
[Bug] In firefox search dont work

### ISSUE THREAD

**Issue by ss14husky** [SKCro/WebTV-HD#9]
> **Describe the bug**
Firefox blocks search function

> **Steps to reproduce**
Just try search in firefox

> **Expected behavior**
just search

> **Screenshots or video**
> https://imgur.com/a/uokolO3

> **Environment**
Firefox 120.0.1 on Windows (64 bit)

> **Additional context**
> If you have anything else to tell us about the bug, let us know here.

**Comment by SKCro** [comment]
This happens due to an oversight I made where the search doesn't open in a new tab.
This will be fixed next commit, which will be soon.

**Comment by SKCro** [comment]
Fixed with the latest commit (#199).
